[env:esp32dev]
platform = espressif32 @ ~5.4.0
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.filesystem = littlefs
lib_ldf_mode = deep+
lib_deps =
	bblanchon/ArduinoJson @ ^7.0.4
	mathieucarbou/ESPAsyncWebServer @ ^3.6.0
